#pragma once

#include <string>
#include <windows.h>

constexpr int MAZE_WIDTH = 13;
constexpr int MAZE_HEIGHT = 13;
constexpr int NUM_HINTS = 6;
constexpr int MAX_SCORE = 1500;
constexpr int STEP_PENALTY = 5;

const WORD COLOR_DEFAULT = 7;
const WORD COLOR_WALL = FOREGROUND_INTENSITY;
const WORD COLOR_PLAYER = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD COLOR_HINT = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD COLOR_LETTER = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD COLOR_PATH = COLOR_DEFAULT;
const WORD COLOR_FINAL_DOOR_CLOSED = FOREGROUND_RED | FOREGROUND_INTENSITY;
const WORD COLOR_FINAL_DOOR_OPEN = FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD COLOR_STATUS_OK = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD COLOR_STATUS_WARN = FOREGROUND_RED | FOREGROUND_INTENSITY;

inline const std::string H_WALL = "#";