#pragma once

#include <string>
#include <windows.h>

extern HANDLE hConsole;

const WORD COLOR_DEFAULT = 7;
const WORD COLOR_WALL = FOREGROUND_INTENSITY;
const WORD COLOR_PLAYER = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD COLOR_HINT = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD COLOR_LETTER = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD COLOR_PATH = COLOR_DEFAULT;
const WORD COLOR_FINAL_DOOR_CLOSED = FOREGROUND_RED | FOREGROUND_INTENSITY;
const WORD COLOR_FINAL_DOOR_OPEN = FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD COLOR_STATUS_OK = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD COLOR_STATUS_WARN = FOREGROUND_RED | FOREGROUND_INTENSITY;

extern const std::string H_WALL;

void setColor(WORD color);
std::string repeatText(const std::string& s, int count);